### ISSUE TITLE
MAKE IT FOR KOTLIN PLEASE!!!!!!!

### ISSUE THREAD

**Issue by Monabr** [christopherney/Enigma#3]
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

**Comment by djzara** [comment]
Most aggressive enhancement request I've ever seen. Chill dude.

**Comment by christopherney** [comment]
Hi guys, 

First of all thanks for the attention you paid to this project. The Kotlin compatibility is not so easy to implement. 

I have to write a Kotlin parser for that. If anyone wants to join the project to help me, with pleasure.

For now I really busy with my job, but I'm thinking to work on it during my next holidays.

BR

**Comment by Monabr** [comment]
Almost a year for this request (͡° ͜ʖ ͡°)

**Comment by chilex111** [comment]
@christopherney  Please have you been able to come around to making this Kotlin compatible?
I came across your plugin and after successfully building the app, I tried running it on a device but it keeps crashing with this error: 
     ```
   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980)
     Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.indexOf(int)' on a null object reference
        at java.lang.Runtime.loadLibrary0(Runtime.java:1051)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at org.opencv.android.StaticHelper.initOpenCV(StaticHelper.java:33)
        at org.opencv.android.OpenCVLoader.initDebug(OpenCVLoader.java:79)
        at com.initsng.indigo.peripheral.App.onCreate(App.kt:37)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1189)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6488)
        at android.app.ActivityThread.access$1400(ActivityThread.java:226) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1884) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7386) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:980) 
```
I also noticed that the EnigmaUtils is showing _Cannot resolve symbol 'EnigmaUtils'_
